package com.example.findyourjobv;

import java.net.URLEncoder;
import java.util.List;

import com.selectyourjob.models.ResultModel;
import com.selectyourjob.models.SearchParasModel;
import com.selectyourjob.service.JobSearch;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.themes.Runo;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class FindYourJobComposite extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Panel rightPanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private VerticalLayout leftInputLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button searchBT;
	@AutoGenerated
	private TextField jobnameTF;
	@AutoGenerated
	private TextField locationTF;
	@AutoGenerated
	private HorizontalLayout TopBarLayout;
	@AutoGenerated
	private MenuBar naviBar;
	@AutoGenerated
	private Label logoLabel;
	
	private Label sponsorLabel;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	Navigator navigator;

	List<ResultModel> resultModels;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public FindYourJobComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1050px");
		mainLayout.setHeight("650px");
		mainLayout.setMargin(true);

		// top-level component properties
//		setWidth("100.0%");
//		setHeight("100.0%");

		// TopBarLayout
		TopBarLayout = buildTopBarLayout();
		mainLayout.addComponent(TopBarLayout);
		mainLayout.setExpandRatio(TopBarLayout, 1.0f);

		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setExpandRatio(horizontalLayout_2, 7.0f);

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setExpandRatio(horizontalLayout_1, 1.0f);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildTopBarLayout() {
		// common part: create layout
		TopBarLayout = new HorizontalLayout();
		TopBarLayout.setImmediate(false);
		TopBarLayout.setWidth("1050px");
		TopBarLayout.setHeight("100px");
		TopBarLayout.setMargin(true);

		// logoLabel
		logoLabel = new Label();
		logoLabel.setStyleName("v-label");
		logoLabel.setImmediate(false);
		logoLabel.setWidth("100.0%");
		logoLabel.setHeight("100.0%");
		logoLabel.setValue("Find Your Job Here");
		logoLabel.addStyleName(Runo.LABEL_H1);
		TopBarLayout.addComponent(logoLabel);

		// naviBar
		naviBar = new MenuBar();
		naviBar.setImmediate(false);
		naviBar.setWidth("-1px");
		naviBar.setHeight("-1px");
		TopBarLayout.addComponent(naviBar);

		return TopBarLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("1050px");
		horizontalLayout_2.setHeight("450px");
		horizontalLayout_2.setMargin(false);

		// leftInputLayout
		leftInputLayout = buildLeftInputLayout();
		horizontalLayout_2.addComponent(leftInputLayout);
		horizontalLayout_2.setExpandRatio(leftInputLayout, 3.0f);

		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		horizontalLayout_2.addComponent(horizontalLayout_3);
		horizontalLayout_2.setExpandRatio(horizontalLayout_3, 7.0f);

		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildLeftInputLayout() {
		// common part: create layout
		leftInputLayout = new VerticalLayout();
		leftInputLayout.setImmediate(false);
		leftInputLayout.setWidth("250px");
		leftInputLayout.setHeight("100.0%");
		leftInputLayout.setMargin(true);

		// locationTF
		locationTF = new TextField();
		locationTF.setCaption("Location:");
		locationTF.setImmediate(false);
		locationTF.setWidth("250px");
//		locationTF.setHeight("30px");
		locationTF.setRequired(true);
		leftInputLayout.addComponent(locationTF);
//		leftInputLayout.setExpandRatio(locationTF, 1.0f);

		// jobnameTF
		jobnameTF = new TextField();
		jobnameTF.setCaption("Keywords:");
		jobnameTF.setImmediate(false);
		jobnameTF.setWidth("250px");
//		jobnameTF.setHeight("30px");
		jobnameTF.setRequired(true);
		leftInputLayout.addComponent(jobnameTF);
		leftInputLayout.setExpandRatio(jobnameTF, 1.0f);

		// searchBT
		searchBT = new Button();
		searchBT.setCaption("Search");
		searchBT.setImmediate(true);
		searchBT.setWidth("-1px");
		searchBT.setHeight("-1px");
		searchBT.addStyleName(Runo.BUTTON_DEFAULT);
		leftInputLayout.addComponent(searchBT);
		leftInputLayout.setExpandRatio(searchBT, 1.0f);
		leftInputLayout.setComponentAlignment(searchBT, new Alignment(34));
		searchBT.addClickListener(new Button.ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
//				rightPanel.setHeight("-1px");
				verticalLayout_2.setHeight("-1px");
				SearchParasModel spm = new SearchParasModel();
				spm.setL(URLEncoder.encode(locationTF.getValue()));
				spm.setQ(URLEncoder.encode(jobnameTF.getValue()));
				// searchBT.setCaption("test");
				JobSearch jobSearch = new JobSearch();
				resultModels = jobSearch.search(spm);
				showresult();
			}
		});

		// panel_1
		panel_1 = buildPanel_1();
		leftInputLayout.addComponent(panel_1);
		leftInputLayout.setExpandRatio(panel_1, 6.0f);

		return leftInputLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("250px");
		panel_1.setHeight("310px");
		panel_1.setCaption("Sponsor");
		panel_1.addStyleName(Runo.PANEL_LIGHT);
		
		// 
	
//		panel_1.setContent(sponsorLabel);

		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		panel_1.setContent(verticalLayout_3);
		
		sponsorLabel = new Label();
//		sponsorLabel.setStyleName("v-label");
		sponsorLabel.setImmediate(false);
		sponsorLabel.setWidth("100.0%");
		sponsorLabel.setHeight("100.0%");
		sponsorLabel.setContentMode(ContentMode.HTML);
		sponsorLabel.setValue("<a target=\"_blank\" href=\"http://www.shareasale.com/r.cfm?b=511528&u=863409&m=49065&urllink=&afftrack=\"><img src=\"http://www.shareasale.com/image/49065/GMSS-250x250.gif\"  border=\"0\"></a>");
//		sponsorLabel.addStyleName(Runo.LABEL_H1);
		verticalLayout_3.addComponent(sponsorLabel);
		return panel_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("800px");
		horizontalLayout_3.setHeight("100.0%");
		horizontalLayout_3.setMargin(true);

		// rightPanel
		rightPanel = buildRightPanel();
		horizontalLayout_3.addComponent(rightPanel);

		return horizontalLayout_3;
	}

	@AutoGenerated
	private Panel buildRightPanel() {
		// common part: create layout
		rightPanel = new Panel();
		rightPanel.setCaption("Search Results");
		rightPanel.setImmediate(false);
		rightPanel.setWidth("800px");
		rightPanel.setHeight("450px");

		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		rightPanel.setContent(verticalLayout_2);

		return rightPanel;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("1050px");
		horizontalLayout_1.setHeight("50px");
		horizontalLayout_1.setMargin(true);

		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("50px");
		label_1.setValue("<span id=indeed_at><a href=\"http://www.indeed.com/\">jobs</a>"
				+ " by <ahref=\"http://www.indeed.com/\" title=\"Job Search\">"
				+ "<img src=\"http://www.indeed.com/p/jobsearch.gif\" style=\"border: 0; "
				+ "vertical-align: middle;\" alt=\"Indeed job search\"></a></span>   Copyright 2014 selecyourgoods.com all reserved.");
		label_1.setContentMode(ContentMode.HTML);
		horizontalLayout_1.addComponent(label_1);

		return horizontalLayout_1;
	}

	private void showresult() {
		verticalLayout_2.removeAllComponents();
		int i=0;
		if (resultModels != null) {
			for (ResultModel rm : resultModels) {
				SearchResultComposite src = new SearchResultComposite();
				src.setSearchResult(rm);
				verticalLayout_2.addComponent(src);
//				if(++i==2)
//				break;
			}
		}
	}

}
